spring: 
  profile:
    active:
      -dev

---
spring:
    application:
      name: springCloud-config-dev
    profile: dev  #开发环境

---
spring:
  application: 
    name: springCloud-config-dev
  profile: test #测试环境
#保存为UTF-8格式

