spring: 
  profile:
    active:
      -dev

---
spring:
  profile: dev  #开发环境
    application:
      name: springcloud-config-dev

---
spring:
  profile: test #测试环境
  application: 
    name: springcloud-config-dev
#保存为UTF-8格式

